package com.polyflux.ulpf.inference;

import com.polyflux.ulpf.parser.Parsed;
import com.polyflux.ulpf.schema.Ues.FieldSuggestion;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.stereotype.Component;

@Component
public class InferenceService {
    private record Alias(String regex,String target,String type) { }
    private static final List<Alias> ALIASES=List.of(
      new Alias("(?i)^(src|srcip|src_ip|sip|source_ip|source|source_address|client_ip|clientip|remip|src_addr|saddr|c_ip)$","network.source_ip","ip"),new Alias("(?i)^(dst|dstip|dst_ip|dip|destination_ip|destination|destination_address|dest_ip|dest|server_ip|daddr|dst_addr)$","network.destination_ip","ip"),new Alias("(?i)^(spt|srcport|src_port|sport|source_port|client_port)$","network.source_port","port"),new Alias("(?i)^(dpt|dstport|dst_port|dport|destination_port|dest_port|port|server_port)$","network.destination_port","port"),new Alias("(?i)^(proto|protocol|ip_proto|transport)$","network.protocol","protocol"),new Alias("(?i)^(act|action|decision|decision_code|policy_action|disposition|verdict|result|status)$","event.action","enum"),new Alias("(?i)^(user|username|usrname|suser|account|user_name|login)$","identity.username","string"),new Alias("(?i)^(severity|level|sev|priority|pri|risk|risk_level|threat_level)$","event.severity","severity"),new Alias("(?i)^(policy|rule|policyname|rule_name|acl|access_group)$","rule.name","string"),new Alias("(?i)^(rule_id|policyid|sig_id|signature_id)$","rule.id","string"),new Alias("(?i)^(alert_code|event_type|event_name)$","event.type","string"),new Alias("(?i)^(timestamp|@timestamp|time|ts|datetime|event_time|eventtime|date_time)$","timestamps.event_time","timestamp"),new Alias("(?i)^(_host|host|hostname|devname|device)$","source.device_id","string"));
    public List<FieldSuggestion> suggest(Parsed p){Set<String> taken=new HashSet<>();List<FieldSuggestion> out=new ArrayList<>();for(var f:p.fields.entrySet()){String shape=shape(f.getValue());Alias a=ALIASES.stream().filter(x->f.getKey().matches(x.regex)).findFirst().orElse(null);if(a!=null&&!taken.contains(a.target)&&(compatible(shape,a.type)||a.type.equals("protocol")&&f.getValue().matches("\\d{1,3}"))){taken.add(a.target);out.add(new FieldSuggestion(f.getKey(),f.getValue(),a.target,.9,"field name \""+f.getKey()+"\" matches alias dictionary; value shape "+shape));}else out.add(new FieldSuggestion(f.getKey(),f.getValue(),null,0,""));}
      for(int i=0;i<out.size();i++){var s=out.get(i);if(s.target()!=null)continue;String shape=shape(s.sample()), target=null,why="unrecognized ("+shape+"); kept in extensions";double c=0;String key=s.source_field();if(shape.equals("ip")){target=taken.contains("network.source_ip")?"network.destination_ip":"network.source_ip";c=taken.contains(target)?0:.6;why="IP-shaped value";}else if(shape.equals("protocol")){target="network.protocol";c=.8;why="value is a protocol name";}else if(shape.equals("action")){target="event.action";c=.8;why="value is a known action verb";}else if(shape.equals("timestamp")){target="timestamps.event_time";c=.75;why="value parses as a timestamp";}else if(shape.equals("port")&&key.matches("(?i).*port|pt$")){target=key.matches("(?i)^(spt|srcport|src_port|sport|source_port|client_port)$")?"network.source_port":"network.destination_port";c=.6;why="port-range integer with port-like name";}else if(shape.equals("number")&&key.matches("(?i).*(severity|level|priority|sev)$")){target="event.severity";c=.55;why="numeric severity field";}if(target!=null&&c>0&&!taken.contains(target)){taken.add(target);out.set(i,new FieldSuggestion(s.source_field(),s.sample(),target,c,why));}else out.set(i,new FieldSuggestion(s.source_field(),s.sample(),null,0,why));}
      return out;}
    private String shape(String v){String x=v.trim();if(x.matches("(?i)^(25[0-5]|2[0-4]\\d|1?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}$"))return"ip";if(x.matches("(?i)^(tcp|udp|icmp|gre|esp)$"))return"protocol";if(x.matches("(?i)^(accept|allow|allowed|permit|permitted|pass|deny|denied|drop|dropped|block|blocked|blocked_by_policy|reject|rejected|failed|failure|login_failure|login_success|success|alert|detected|built|ssl-login-fail|auth-reject|tunnel-up|auth-success|login-success)$"))return"action";if(x.matches("^\\d{4}-\\d\\d-\\d\\d(?:[T ].*)?$|^\\d{10}|^\\d{13}$"))return"timestamp";if(x.matches("^\\d{1,5}$")&&Integer.parseInt(x)<=65535)return"port";if(x.matches("^-?\\d+(\\.\\d+)?$"))return"number";return"string";}
    private boolean compatible(String shape,String type){return type.equals("string")||type.equals("severity")||type.equals(shape)||type.equals("enum")&&shape.equals("action")||type.equals("int")&&shape.equals("number")||type.equals("timestamp")&&shape.equals("date");}
}
