package com.polyflux.ulpf.normalization;

import com.polyflux.ulpf.parser.Parsed;
import com.polyflux.ulpf.schema.Ues;
import com.polyflux.ulpf.schema.Ues.Mapping;
import com.polyflux.ulpf.schema.Ues.MappingEntry;
import com.polyflux.ulpf.schema.Ues.Raw;
import java.net.InetAddress;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.springframework.stereotype.Component;

@Component
public class NormalizationService {
    private static final Map<String,String> ACTION=Map.ofEntries(Map.entry("accept","allow"),Map.entry("allow","allow"),Map.entry("allowed","allow"),Map.entry("permit","allow"),Map.entry("permitted","allow"),Map.entry("pass","allow"),Map.entry("built","allow"),Map.entry("close","allow"),Map.entry("deny","deny"),Map.entry("denied","deny"),Map.entry("drop","deny"),Map.entry("dropped","deny"),Map.entry("block","deny"),Map.entry("blocked","deny"),Map.entry("blocked_by_policy","deny"),Map.entry("reject","deny"),Map.entry("rejected","deny"),Map.entry("client-rst","reset"),Map.entry("server-rst","reset"),Map.entry("reset","reset"),Map.entry("ssl-login-fail","login_failure"),Map.entry("auth-reject","login_failure"),Map.entry("failed","login_failure"),Map.entry("login-fail","login_failure"),Map.entry("failure","login_failure"),Map.entry("tunnel-up","login_success"),Map.entry("auth-success","login_success"),Map.entry("login-success","login_success"),Map.entry("success","login_success"),Map.entry("alert","alert"),Map.entry("detected","alert"));
    private static final Map<String,Integer> SEVERITY=Map.ofEntries(Map.entry("emerg",10),Map.entry("emergency",10),Map.entry("alert",9),Map.entry("crit",8),Map.entry("critical",8),Map.entry("err",7),Map.entry("error",7),Map.entry("warning",6),Map.entry("warn",6),Map.entry("notice",4),Map.entry("notification",4),Map.entry("info",2),Map.entry("information",2),Map.entry("informational",2),Map.entry("debug",0));
    private static final int[] PRI={10,9,8,7,6,4,2,0};
    private static final Map<String,String> PROTO=Map.of("1","icmp","6","tcp","17","udp","47","gre","50","esp","58","ipv6-icmp");
    private static final Map<Integer,String> SERVICES=Map.ofEntries(Map.entry(20,"ftp-data"),Map.entry(21,"ftp"),Map.entry(22,"ssh"),Map.entry(23,"telnet"),Map.entry(25,"smtp"),Map.entry(53,"dns"),Map.entry(80,"http"),Map.entry(110,"pop3"),Map.entry(123,"ntp"),Map.entry(143,"imap"),Map.entry(443,"https"),Map.entry(445,"smb"),Map.entry(3306,"mysql"),Map.entry(3389,"rdp"),Map.entry(4444,"metasploit-default"),Map.entry(8080,"http-alt"));
    public Map<String,Object> empty(Raw raw,Parsed parsed){return Ues.event(Ues.eventId(raw.raw_event_id()),raw,parsed);}
    public Map<String,Object> normalize(Raw raw,Parsed p,Mapping mapping,List<String> uncertainOverride){Map<String,Object> ev=empty(raw,p);Map<String,Object> usedMap=new LinkedHashMap<>();Set<String> used=new HashSet<>(),uncertain=new java.util.LinkedHashSet<>(uncertainOverride);List<Double> confidence=new ArrayList<>();int required=0,missing=0;String eventTimeField=p.fields.keySet().stream().filter(k->k.matches("(?i)^(timestamp|@timestamp|time|ts|datetime|event_time|eventtime|date_time)$")).findFirst().orElse(null);if(eventTimeField!=null)try{Ues.child(ev,"timestamps").put("event_time",com.polyflux.ulpf.parser.LogParser.toInstant(p.fields.get(eventTimeField)));Ues.child(ev,"timestamps").put("event_time_inferred",false);}catch(Exception ignored){}
      for(int i=0;i<mapping.entries().size();i++){MappingEntry e=mapping.entries().get(i);if(Boolean.TRUE.equals(e.required()))required++;String key=find(p.fields,e.source_field());String v=key==null?null:p.fields.get(key);if(v==null||v.isEmpty()){boolean alternative=mapping.entries().stream().anyMatch(x->x!=e&&x.target().equals(e.target())&&find(p.fields,x.source_field())!=null);if(Boolean.TRUE.equals(e.required())&&!alternative){missing++;uncertain.add(e.target());}continue;}
        Object current=getPath(ev,e.target());if(current!=null&&!e.target().startsWith("extensions")){used.add(key);continue;}Coerced c=coerce(v,e);used.add(key);if(!c.ok){uncertain.add(e.target());continue;}setPath(ev,e.target(),c.value);if(e.target().equals("event.severity"))Ues.child(ev,"event").put("original_severity",v);List<String> transforms=new ArrayList<>(e.transforms()==null?List.of():e.transforms());for(String t:c.transforms)if(!transforms.contains(t))transforms.add(t);Map<String,Object> lin=Ues.map("source_field",key,"mapping",mapping.mapping_id()+"@"+mapping.version()+"#"+(i+1),"transforms",transforms,"confidence",e.confidence(),"raw_value",v);int[] span=p.spans.get(key);if(span!=null)lin.put("raw_span",span);Ues.child(ev,"lineage").put(e.target(),lin);confidence.add(e.confidence());}
      p.fields.forEach((k,v)->{if(!used.contains(k))usedMap.put(k,v);});Ues.child(Ues.child(ev,"extensions"),"vendor_specific").clear();Ues.child(Ues.child(ev,"extensions"),"vendor_specific").putAll(usedMap);
      Map<String,Object> event=Ues.child(ev,"event");String action=(String)event.get("action");if(action!=null){event.put("outcome",action.equals("allow")||action.equals("login_success")?"success":List.of("deny","login_failure","reset").contains(action)?"failure":"unknown");event.put("category",action.startsWith("login")?"authentication":action.equals("alert")?"intrusion_detection":"network");if(event.get("type")==null)event.put("type",action.startsWith("login")?"authentication":"connection");}
      Map<String,Object> net=Ues.child(ev,"network"),enrich=Ues.child(ev,"enrichment");String src=(String)net.get("source_ip"),dst=(String)net.get("destination_ip");if(src!=null)enrich.put("source_ip_class",isPrivate(src)?"private":"public");if(dst!=null)enrich.put("destination_ip_class",isPrivate(dst)?"private":"public");Object port=net.get("destination_port");if(port instanceof Number n&&SERVICES.containsKey(n.intValue()))enrich.put("destination_service",SERVICES.get(n.intValue()));if(net.get("direction")==null&&src!=null&&dst!=null){boolean s=isPrivate(src),d=isPrivate(dst);net.put("direction",s&&!d?"outbound":!s&&d?"inbound":s?"internal":"external");}
      double avg=confidence.stream().mapToDouble(Double::doubleValue).average().orElse(0);double reqPenalty=required==0?0:(double)missing/required;double uncPenalty=Math.min(.5,uncertain.size()*.1);Ues.child(ev,"normalization").putAll(Ues.map("status",confidence.isEmpty()?"RAW_ONLY":!uncertain.isEmpty()||missing>0?"PARTIAL":"NORMALIZED","mapping_id",mapping.mapping_id(),"mapping_version",mapping.version(),"quality",Math.round(avg*(1-reqPenalty*.5)*(1-uncPenalty)*100.0)/100.0,"uncertain_fields",new ArrayList<>(uncertain)));return ev;}
    private record Coerced(boolean ok,Object value,List<String> transforms){}
    private Coerced coerce(String raw,MappingEntry e){String v=raw.trim(),type=e.type()==null?"string":e.type();try{return switch(type){case "ip"->{String x=v.replaceAll("^\\[|\\]$","").toLowerCase();boolean ok=x.matches("(?i)^(25[0-5]|2[0-4]\\d|1?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}$")||x.contains(":")&&x.matches("[0-9a-f:]+")&&x.contains("::");yield new Coerced(ok,ok?x:null,List.of("ip_normalize"));}case "port","int"->{int n=Integer.parseInt(v);boolean ok=!type.equals("port")||n>=0&&n<=65535;yield new Coerced(ok,ok?n:null,List.of("to_"+type));}case "protocol"->{String x=PROTO.getOrDefault(v,v.toLowerCase());yield new Coerced(x.matches("[a-z0-9-]{2,12}"),x,List.of(PROTO.containsKey(v)?"protocol_number_to_name":"protocol_lowercase"));}case "enum"->{String x=v.toLowerCase();yield new Coerced(true,e.enum_map()!=null&&e.enum_map().containsKey(x)?e.enum_map().get(x):ACTION.getOrDefault(x,x),List.of("enum_map"));}case "severity"->{String x=v.toLowerCase();int n;if((e.transforms()!=null&&e.transforms().contains("severity_from_pri"))&&x.matches("\\d+")){n=PRI[Integer.parseInt(x)%8];}else if(SEVERITY.containsKey(x))n=SEVERITY.get(x);else if(x.matches("\\d+")){int a=Integer.parseInt(x);n=e.source_field().equals("level")&&a<=7?PRI[a]:Math.min(10,a);}else n=switch(x){case "high"->8;case "medium"->5;case "low"->2;default->-1;};yield new Coerced(n>=0,n>=0?n:null,List.of("severity_normalize"));}case "timestamp"->{Instant i=v.matches("\\d{13}")?Instant.ofEpochMilli(Long.parseLong(v)):v.matches("\\d{10}")?Instant.ofEpochSecond(Long.parseLong(v)):Instant.parse(v.contains("T")?v:v.replace(" ","T")+"Z");yield new Coerced(true,i.toString(),List.of("to_utc_iso8601"));}default->new Coerced(true,v,List.of());};}catch(Exception ignored){return new Coerced(false,null,List.of());}}
    private String find(Map<String,String> f,String key){if(f.containsKey(key))return key;return f.keySet().stream().filter(k->k.equalsIgnoreCase(key)).findFirst().orElse(null);}
    private Object getPath(Map<String,Object> obj,String path){Object cur=obj;for(String key:path.split("\\.")){if(!(cur instanceof Map<?,?> m))return null;cur=m.get(key);}return cur;}
    @SuppressWarnings("unchecked") private void setPath(Map<String,Object> obj,String path,Object value){String[] keys=path.split("\\.");Map<String,Object> cur=obj;for(int i=0;i<keys.length-1;i++)cur=(Map<String,Object>)cur.computeIfAbsent(keys[i],k->new LinkedHashMap<>());cur.put(keys[keys.length-1],value);}
    private boolean isPrivate(String ip){try{return InetAddress.getByName(ip).isSiteLocalAddress()||InetAddress.getByName(ip).isLoopbackAddress()||ip.startsWith("169.254.")||ip.toLowerCase().startsWith("fc")||ip.toLowerCase().startsWith("fd")||ip.toLowerCase().startsWith("fe80");}catch(Exception ex){return false;}}
}
