package com.polyflux.ulpf.ingestion;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.polyflux.ulpf.analytics.RuleAnalytics;
import com.polyflux.ulpf.common.JsonSupport;
import com.polyflux.ulpf.inference.InferenceService;
import com.polyflux.ulpf.normalization.MappingCatalog;
import com.polyflux.ulpf.normalization.NormalizationService;
import com.polyflux.ulpf.parser.LogParser;
import com.polyflux.ulpf.parser.Parsed;
import com.polyflux.ulpf.schema.Ues;
import com.polyflux.ulpf.schema.Ues.FieldSuggestion;
import com.polyflux.ulpf.schema.Ues.Mapping;
import com.polyflux.ulpf.schema.Ues.Raw;
import com.polyflux.ulpf.storage.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.time.Month;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class PipelineService {
    private final RawEvents raws; private final Events events; private final Mappings mappings; private final Bindings bindings;
    private final Proposals proposals; private final Alerts alerts; private final Dlq dlq; private final Drifts drifts; private final Audit audit;
    private final ObjectMapper mapper; private final JsonSupport json; private final LogParser parser; private final MappingCatalog catalog;
    private final NormalizationService normalizer; private final InferenceService inference; private final RuleAnalytics analytics;
    public PipelineService(RawEvents raws,Events events,Mappings mappings,Bindings bindings,Proposals proposals,Alerts alerts,Dlq dlq,Drifts drifts,Audit audit,ObjectMapper mapper,JsonSupport json,LogParser parser,MappingCatalog catalog,NormalizationService normalizer,InferenceService inference,RuleAnalytics analytics){this.raws=raws;this.events=events;this.mappings=mappings;this.bindings=bindings;this.proposals=proposals;this.alerts=alerts;this.dlq=dlq;this.drifts=drifts;this.audit=audit;this.mapper=mapper;this.json=json;this.parser=parser;this.catalog=catalog;this.normalizer=normalizer;this.inference=inference;this.analytics=analytics;}

    @Transactional public Map<String,Object> ingest(String body,String transport,String file){if(body.getBytes(StandardCharsets.UTF_8).length>2*1024*1024)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Payload exceeds 2 MB");String text=body;try{var n=mapper.readTree(body);if(n.isObject()&&n.has("text")){text=n.path("text").asText();transport=n.path("transport").asText(transport);file=n.path("file").asText(file);} }catch(Exception ignored){}
      if(text.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Empty body");List<String> lines=split(text);List<String> header=null;if(lines.size()>1&&looksCsvHeader(lines.getFirst())){header=csv(lines.removeFirst());}
      UUID ingestion=uuid7();List<Map<String,Object>> output=new ArrayList<>();int rejected=0;int index=0;for(String line:lines){index++;if(index>5000||line.getBytes(StandardCharsets.UTF_8).length>65536){rejected++;continue;}Map<String,Object> ctx=new LinkedHashMap<>();if(file!=null&&!file.isBlank())ctx.put("file",file);ctx.put("line",index+(header==null?0:1));if(header!=null)ctx.put("csv_header",header);Raw raw=new Raw(uuid7().toString(),ingestion.toString(),line,sha256(line),line.getBytes(StandardCharsets.UTF_8).length,Ues.now(),transport,ctx);RawEventEntity row=raws.save(new RawEventEntity(UUID.fromString(raw.raw_event_id()),ingestion,line,raw.raw_sha256(),raw.byte_length(),Instant.parse(raw.received_at()),transport,json.write(ctx)));output.add(process(raw,row));}
      audit.save(new AuditEntity("ingest",output.size()+" events via "+transport+(file==null?"":" ("+file+")")));return Map.of("ingestion_id",ingestion.toString(),"accepted",output.size(),"rejected",rejected,"events",output);}

    private Map<String,Object> process(Raw raw,RawEventEntity rawRow){String stage="parse";try{Parsed p=parser.parse(raw);Mapping mapping=null;List<String> uncertain=List.of();BindingEntity binding=bindings.findById(p.sourceKey).orElse(null);if(binding!=null&&p.builtinMapping==null)mapping=findMapping(binding.mappingId,binding.version);else if(p.builtinMapping!=null)mapping=findMapping(p.builtinMapping,null);Map<String,Object> ev;
        if(mapping!=null){if(binding!=null&&p.builtinMapping==null){DriftResult drift=detectDrift(p,mapping);if(drift!=null){uncertain=drift.targets;recordDrift(p,mapping,drift,raw,evPlaceholder(raw,p));}}ev=normalizer.normalize(raw,p,mapping,uncertain);}
        else {ev=normalizer.empty(raw,p);Map<String,Object> norm=Ues.child(ev,"normalization");norm.put("status","RAW_ONLY");if(p.fields.size()>=2)propose(p,raw);}
        String eventId=(String)ev.get("event_id");Instant eventTime;try{eventTime=Instant.parse((String)Ues.child(ev,"timestamps").get("event_time"));}catch(Exception ex){eventTime=Instant.parse(raw.received_at());}
        events.save(new EventEntity(UUID.fromString(eventId),UUID.fromString(raw.raw_event_id()),p.sourceKey,(String)Ues.child(ev,"normalization").get("status"),eventTime,json.write(ev),json.write(Map.of("parser",p.parser,"format",p.format,"fields",p.fields,"spans",p.spans,"selection_reason",p.selectionReason))));dlq.deleteById(UUID.fromString(raw.raw_event_id()));analytics.analyze(ev);return ev;
      }catch(Exception ex){Map<String,Object> d=Map.of("raw_event_id",raw.raw_event_id(),"stage",stage,"error",ex.getClass().getSimpleName()+": "+ex.getMessage(),"attempts",1,"at",Ues.now());dlq.save(new DlqEntity(UUID.fromString(raw.raw_event_id()),json.write(d)));Map<String,Object> ev=normalizer.empty(raw,new Parsed());Ues.child(ev,"normalization").put("status","RAW_ONLY");return ev;}}

    private record DriftResult(double score,List<String> missing,List<String> added,List<Map<String,Object>> renames,List<String> targets){}
    private DriftResult detectDrift(Parsed p,Mapping m){Set<String> present=p.fields.keySet().stream().map(String::toLowerCase).collect(java.util.stream.Collectors.toSet());Set<String> satisfied=m.entries().stream().filter(e->present.contains(e.source_field().toLowerCase())).map(e->e.target()).collect(java.util.stream.Collectors.toSet());List<String> missing=m.entries().stream().filter(e->!present.contains(e.source_field().toLowerCase())&&!satisfied.contains(e.target())).map(e->e.source_field()).toList();if(missing.isEmpty())return null;Set<String> mapped=m.entries().stream().map(e->e.source_field().toLowerCase()).collect(java.util.stream.Collectors.toSet());List<String> added=p.fields.keySet().stream().filter(k->!mapped.contains(k.toLowerCase())&&!k.equals("_host")).toList();List<Map<String,Object>> renames=new ArrayList<>();Set<String> used=new HashSet<>();for(String old:missing){MappingEntryRef ref=m.entries().stream().filter(e->e.source_field().equals(old)).map(e->new MappingEntryRef(e.target(),e.type())).findFirst().orElse(null);if(ref==null)continue;String expect="enum".equals(ref.type)?"action":ref.type;for(String key:added){String shape=shape(p.fields.get(key));if(!used.contains(key)&&(expect.equals("string")||shape.equals(expect)||expect.equals("enum")&&shape.equals("action"))){used.add(key);renames.add(Ues.map("from",old,"to",key,"confidence",expect.equals("string")?.4:.8,"reason","value shape "+shape+" matches "+ref.target));break;}}}return new DriftResult((double)missing.size()/Math.max(1,m.entries().size()),missing,added,renames,missing.stream().map(old->m.entries().stream().filter(e->e.source_field().equals(old)).map(e->e.target()).findFirst().orElse("")).filter(x->!x.isBlank()).toList());}
    private record MappingEntryRef(String target,String type){}
    private void recordDrift(Parsed p,Mapping m,DriftResult d,Raw raw,Map<String,Object> unused){UUID id=uuid7();List<FieldSuggestion> suggestions=new ArrayList<>();for(var e:m.entries()){Map<String,Object> rename=d.renames.stream().filter(x->x.get("from").equals(e.source_field())).findFirst().orElse(null);String key=rename==null?e.source_field():(String)rename.get("to");String value=p.fields.getOrDefault(key,"");suggestions.add(new FieldSuggestion(key,value,e.target(),rename==null?e.confidence():((Number)rename.get("confidence")).doubleValue(),rename==null?"unchanged":"renamed from "+e.source_field()));if(rename!=null)suggestions.add(new FieldSuggestion(e.source_field(),"",e.target(),.9,"legacy alias kept for backward compatibility"));}
      UUID pid=uuid7();Map<String,Object> report=Ues.map("id",id.toString(),"source_key",p.sourceKey,"mapping_id",m.mapping_id(),"from_version",m.version(),"score",Math.round(d.score*100.0)/100.0,"missing",d.missing,"added",d.added,"renames",d.renames,"affected_targets",d.targets,"created_at",Ues.now(),"event_id",Ues.eventId(raw.raw_event_id()).toString(),"proposal_id",pid.toString());drifts.save(new DriftEntity(id,p.sourceKey,json.write(report)));Map<String,Object> proposal=Ues.map("id",pid.toString(),"kind","drift","source_key",p.sourceKey,"status","pending","created_at",Ues.now(),"base_mapping",Map.of("mapping_id",m.mapping_id(),"version",m.version()),"suggestions",suggestions,"evidence_raw_ids",List.of(raw.raw_event_id()),"drift_id",id.toString());proposals.save(new ProposalEntity(pid,p.sourceKey,"drift","pending",json.write(proposal)));}
    private void propose(Parsed p,Raw raw){List<ProposalEntity> existing=proposals.findBySourceKeyAndStatus(p.sourceKey,"pending");if(!existing.isEmpty()){Map<String,Object> doc=json.readMap(existing.getFirst().document);@SuppressWarnings("unchecked") List<String> ids=(List<String>)doc.get("evidence_raw_ids");if(!ids.contains(raw.raw_event_id()))ids.add(raw.raw_event_id());existing.getFirst().document=json.write(doc);return;}UUID id=uuid7();Map<String,Object> doc=Ues.map("id",id.toString(),"kind","new_source","source_key",p.sourceKey,"status","pending","created_at",Ues.now(),"suggestions",inference.suggest(p),"evidence_raw_ids",List.of(raw.raw_event_id()));proposals.save(new ProposalEntity(id,p.sourceKey,"new_source","pending",json.write(doc)));audit.save(new AuditEntity("proposal.created","unknown source "+p.sourceKey));}
    private Mapping findMapping(String id,String version){List<MappingEntity> all=mappings.findAllByOrderByMappingIdAscVersionDesc();for(MappingEntity row:all)if(row.mappingId.equals(id)&&(version==null||row.version.equals(version)))try{return mapper.readValue(row.document,Mapping.class);}catch(Exception ignored){}return null;}
    @Transactional public Map<String,Object> state(){seedMappings();Map<String,Object> out=new LinkedHashMap<>();out.put("raws",raws.findAllByOrderByReceivedAtDesc().stream().map(this::rawDoc).toList());out.put("events",events.findAllByOrderByEventTimeDesc().stream().map(e->json.readMap(e.document)).toList());out.put("mappings",mappings.findAllByOrderByMappingIdAscVersionDesc().stream().map(m->{try{return mapper.readValue(m.document,Map.class);}catch(Exception e){return Map.of();}}).toList());Map<String,Object> bind=new LinkedHashMap<>();bindings.findAll().forEach(b->bind.put(b.sourceKey,Map.of("mapping_id",b.mappingId,"version",b.version)));out.put("bindings",bind);out.put("proposals",proposals.findAllByOrderByCreatedAtDesc().stream().map(p->json.readMap(p.document)).toList());out.put("drift",drifts.findAllByOrderByCreatedAtDesc().stream().map(d->json.readMap(d.document)).toList());out.put("alerts",alerts.findAllByOrderByCreatedAtDesc().stream().map(a->json.readMap(a.document)).toList());out.put("dlq",dlq.findAllByOrderByCreatedAtDesc().stream().map(d->json.readMap(d.document)).toList());out.put("audit",audit.findTop300ByOrderByAtDesc().stream().map(a->Ues.map("at",a.at.toString(),"action",a.action,"detail",a.detail)).toList());return out;}
    @Transactional public void seedMappings(){for(Mapping m:catalog.builtins()){MappingEntity.Key key=new MappingEntity.Key(m.mapping_id(),m.version());if(!mappings.existsById(key))mappings.save(new MappingEntity(m.mapping_id(),m.version(),m.parser(),m.source_key(),true,json.write(m)));}}
    private Map<String,Object> rawDoc(RawEventEntity r){Map<String,Object> c=json.readMap(r.contextJson);return Ues.map("raw_event_id",r.id.toString(),"ingestion_id",r.ingestionId.toString(),"raw_text",r.rawText,"raw_sha256",r.sha256,"byte_length",r.byteLength,"received_at",r.receivedAt.toString(),"transport",r.transport,"ingestion_context",c);}
    @Transactional public Map<String,Object> approve(String id,List<FieldSuggestion> edits){ProposalEntity row=proposals.findById(UUID.fromString(id)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Pending proposal not found"));Map<String,Object> p=json.readMap(row.document);if(!"pending".equals(p.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Proposal is no longer pending");List<FieldSuggestion> sug=edits==null?mapper.convertValue(p.get("suggestions"),new TypeReference<>(){}):edits;String mid,ver="1.0";Object base=p.get("base_mapping");if(base instanceof Map<?,?> b){mid=(String)b.get("mapping_id");ver=(Integer.parseInt(((String)b.get("version")).split("\\.")[0])+1)+".0";}else mid="gen-"+row.sourceKey.replaceFirst("^[a-z]+:","").toLowerCase().replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");Mapping m=catalog.generated(mid,ver,row.sourceKey,sug);mappings.save(new MappingEntity(mid,ver,m.parser(),row.sourceKey,false,json.write(m)));bindings.save(new BindingEntity(row.sourceKey,mid,ver));p.put("status","approved");p.put("decided_at",Ues.now());row.status="approved";row.document=json.write(p);proposals.save(row);List<RawEventEntity> sourceRaws=raws.findAllByOrderByReceivedAtDesc().stream().filter(r->events.findById(Ues.eventId(r.id.toString())).map(e->e.sourceKey.equals(row.sourceKey)).orElse(false)).toList();for(RawEventEntity r:sourceRaws)process(toRaw(r),r);audit.save(new AuditEntity("proposal.approved",mid+"@"+ver+" bound to "+row.sourceKey));return Map.of("ok",true,"mapping",m);}
    @Transactional public void reject(String id){ProposalEntity p=proposals.findById(UUID.fromString(id)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Pending proposal not found"));if(!p.status.equals("pending"))throw new ResponseStatusException(HttpStatus.CONFLICT,"Proposal is no longer pending");p.status="rejected";Map<String,Object> d=json.readMap(p.document);d.put("status","rejected");d.put("decided_at",Ues.now());p.document=json.write(d);proposals.save(p);audit.save(new AuditEntity("proposal.rejected",p.sourceKey));}
    @Transactional public int reprocess(){int n=0;for(RawEventEntity r:raws.findAllByOrderByReceivedAtDesc()){process(toRaw(r),r);n++;}audit.save(new AuditEntity("reprocess",n+" raw events reprocessed"));return n;}
    @Transactional public void retryDlq(){for(DlqEntity d:dlq.findAllByOrderByCreatedAtDesc())raws.findById(d.rawEventId).ifPresent(r->process(toRaw(r),r));}
    @Transactional public void reset(){events.deleteAllInBatch();dlq.deleteAllInBatch();raws.deleteAllInBatch();proposals.deleteAllInBatch();drifts.deleteAllInBatch();alerts.deleteAllInBatch();bindings.deleteAllInBatch();mappings.deleteAllInBatch();audit.deleteAllInBatch();seedMappings();}
    private Raw toRaw(RawEventEntity r){return new Raw(r.id.toString(),r.ingestionId.toString(),r.rawText,r.sha256,r.byteLength,r.receivedAt.toString(),r.transport,json.readMap(r.contextJson));}
    private Map<String,Object> evPlaceholder(Raw raw,Parsed p){return normalizer.empty(raw,p);}
    private String shape(String v){if(v==null)return"string";if(v.matches("(?i)^(25[0-5]|2[0-4]\\d|1?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}$"))return"ip";if(v.matches("(?i)^(tcp|udp|icmp|gre|esp)$"))return"protocol";if(v.matches("(?i)^(allow|accept|deny|drop|block|failed|success|alert)$"))return"action";if(v.matches("^\\d{4}-.*|^\\d{13}$"))return"timestamp";if(v.matches("^\\d{1,5}$")&&Integer.parseInt(v)<=65535)return"port";return v.matches("^-?\\d+(\\.\\d+)?$")?"number":"string";}
    private List<String> split(String text){try{var n=mapper.readTree(text);if(n.isArray()){List<String> out=new ArrayList<>();n.forEach(x->out.add(x.isTextual()?x.asText():x.toString()));return out;}if(n.isObject())return List.of(n.toString());}catch(Exception ignored){}return new ArrayList<>(text.lines().filter(x->!x.isBlank()).toList());}
    private static boolean looksCsvHeader(String line){String[] x=line.split(",");return x.length>=3&&java.util.Arrays.stream(x).allMatch(v->v.trim().matches("[A-Za-z_][\\w .-]*"));}
    private static List<String> csv(String line){return List.of(line.split(",",-1)).stream().map(String::trim).toList();}
    private static String sha256(String x){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(b);}catch(Exception e){throw new IllegalStateException(e);}}
    private static UUID uuid7(){long ms=System.currentTimeMillis();byte[] b=new byte[16];new java.security.SecureRandom().nextBytes(b);for(int i=5;i>=0;i--){b[i]=(byte)ms;ms>>>=8;}b[6]=(byte)((b[6]&0x0f)|0x70);b[8]=(byte)((b[8]&0x3f)|0x80);long hi=0,lo=0;for(int i=0;i<8;i++)hi=(hi<<8)|(b[i]&255L);for(int i=8;i<16;i++)lo=(lo<<8)|(b[i]&255L);return new UUID(hi,lo);}
}
