/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ApiPublicV1EventsRouteImport } from './routes/api/public/v1/events'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EventsRoute = ApiPublicV1EventsRouteImport.update({
  id: '/api/public/v1/events',
  path: '/api/public/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/mappings': typeof MappingsRoute
  '/proposals': typeof ProposalsRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/mappings': typeof MappingsRoute
  '/proposals': typeof ProposalsRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drift': typeof DriftRoute
  '/events': typeof EventsRoute
  '/graph': typeof GraphRoute
  '/mappings': typeof MappingsRoute
  '/proposals': typeof ProposalsRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drift'
    | '/events'
    | '/graph'
    | '/mappings'
    | '/proposals'
    | '/api/public/v1/events'
    | '/api/public/v1/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drift'
    | '/events'
    | '/graph'
    | '/mappings'
    | '/proposals'
    | '/api/public/v1/events'
    | '/api/public/v1/health'
  id:
    | '__root__'
    | '/'
    | '/drift'
    | '/events'
    | '/graph'
    | '/mappings'
    | '/proposals'
    | '/api/public/v1/events'
    | '/api/public/v1/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriftRoute: typeof DriftRoute
  EventsRoute: typeof EventsRoute
  GraphRoute: typeof GraphRoute
  MappingsRoute: typeof MappingsRoute
  ProposalsRoute: typeof ProposalsRoute
  ApiPublicV1EventsRoute: typeof ApiPublicV1EventsRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/events': {
      id: '/api/public/v1/events'
      path: '/api/public/v1/events'
      fullPath: '/api/public/v1/events'
      preLoaderRoute: typeof ApiPublicV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriftRoute: DriftRoute,
  EventsRoute: EventsRoute,
  GraphRoute: GraphRoute,
  MappingsRoute: MappingsRoute,
  ProposalsRoute: ProposalsRoute,
  ApiPublicV1EventsRoute: ApiPublicV1EventsRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
